# -*- coding: utf-8 -*-
"""Telecom Network Call Drop Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CaWo-RTMfoeGlE1fEPRto-JtWkEPEMQG

#Telecom-Network-Call-Drop-Analysis

Telecom Network Call Drop Analysis is an EDA-based Python project that analyzes telecom call drop behavior to assess network quality. It evaluates the impact of traffic, weather, time slots, and cell sites using statistical summaries and visualizations.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

sns.set(style="whitegrid")

"""# -------------------------------
# Create output folder
# -------------------------------
"""

os.makedirs("outputs", exist_ok=True)

"""# -------------------------------
# 1. Load Dataset
# -------------------------------
"""

df = pd.read_csv(r"Telco.csv")

print("\n========== DATASET LOADED ==========")
print("Total Rows:", df.shape[0])
print("Total Columns:", df.shape[1])
print("\nColumns:")
print(df.columns.tolist())
print("\n========== SAMPLE DATA ==========")
print(df.head())

"""# -------------------------------
# 2. Feature Engineering
# -------------------------------
"""

df["Call_Drop_Rate"] = (df["Call_Dropped"] / df["Total Calls"]) * 100

print("\n========== SAMPLE DATA ==========")
print(df.head())
print("\n========== FEATURE ENGINEERING COMPLETED ==========")

"""# -------------------------------
# 3. Overall Call Drop Rate
# -------------------------------
"""

overall_drop_rate = (df["Call_Dropped"].sum() / df["Total Calls"].sum()) * 100
print("\nOverall Call Drop Rate:", round(overall_drop_rate, 2), "%")

"""# -------------------------------
# 4. Traffic-wise Analysis
# -------------------------------
"""

traffic_avg = df.groupby("Traffic")["Call_Drop_Rate"].mean()
print("\nTraffic-wise Average Call Drop Rate:")
print(traffic_avg)

plt.figure(figsize=(6,4))
traffic_avg.plot(kind="bar")
plt.title("Traffic vs Call Drop Rate")
plt.ylabel("Call Drop Rate (%)")
plt.tight_layout()
plt.savefig("outputs/traffic_vs_call_drop.png")
plt.show()
plt.close()
plt.clf()
plt.cla()
plt.close("all")

"""# -------------------------------
# 5. Weather-wise Analysis
# -------------------------------
"""

weather_avg = df.groupby("Weather")["Call_Drop_Rate"].mean().sort_values(ascending=False)
print("\nWeather-wise Average Call Drop Rate:")
print(weather_avg)

plt.figure(figsize=(8,4))
weather_avg.plot(kind="bar")
plt.title("Weather Impact on Call Drop Rate")
plt.ylabel("Call Drop Rate (%)")
plt.tight_layout()
plt.savefig("outputs/weather_vs_call_drop.png")
plt.show()

"""# -------------------------------
# 6. Distribution (Histogram)
# -------------------------------
"""

print("\nCall Drop Rate Statistics:")
print(df["Call_Drop_Rate"].describe())

plt.figure(figsize=(6,4))
plt.hist(df["Call_Drop_Rate"], bins=20)
plt.title("Distribution of Call Drop Rate")
plt.xlabel("Call Drop Rate (%)")
plt.ylabel("Frequency")
plt.tight_layout()
plt.savefig("outputs/call_drop_distribution.png")
plt.show()
plt.Colorizer()
plt.close()
plt.clf()
plt.cla()
plt.close("all")

"""# -------------------------------
# 7. Traffic vs Call Drop (Boxplot)
# -------------------------------
"""

plt.figure(figsize=(6,4))
sns.boxplot(x="Traffic", y="Call_Drop_Rate", data=df)
plt.title("Traffic Level vs Call Drop Rate")
plt.tight_layout()
plt.savefig("outputs/traffic_boxplot.png")
plt.show()
plt.close()
plt.clf()
plt.cla()
plt.close("all")

"""# -------------------------------
# 8. Correlation Heatmap
# -------------------------------
"""

corr = df[["Total Calls", "Call_Dropped", "Call_Drop_Rate"]].corr()
print("\nCorrelation Matrix:")
print(corr)

plt.figure(figsize=(5,4))
sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.tight_layout()
plt.savefig("outputs/correlation_heatmap.png")
plt.show()
plt.close()
plt.clf()
plt.cla()
plt.close("all")

"""# -------------------------------
# 9. Time Slot Analysis
# -------------------------------
"""

time_avg = df.groupby("Start_Time_HH_MM_SS_s")["Call_Drop_Rate"].mean()
print("\nTime Slot-wise Call Drop Rate:")
print(time_avg)

plt.figure(figsize=(10,4))
time_avg.plot(marker="o")
plt.title("Time Slot vs Call Drop Rate")
plt.ylabel("Call Drop Rate (%)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("outputs/time_slot_analysis.png")
plt.show()
plt.close()
plt.clf()
plt.cla()
plt.close("all")

"""# -------------------------------
# 10. Top 10 Worst Sites
# -------------------------------
"""

site_avg = df.groupby("outgoing_site_id")["Call_Drop_Rate"].mean().sort_values(ascending=False)
print("\nTop 10 Sites with Highest Call Drop Rate:")
print(site_avg.head(10))

plt.figure(figsize=(8,4))
site_avg.head(10).plot(kind="bar")
plt.title("Top 10 High Call Drop Sites")
plt.ylabel("Call Drop Rate (%)")
plt.tight_layout()
plt.savefig("outputs/top_10_sites.png")
plt.show()
plt.close()
plt.clf()
plt.cla()
plt.close("all")

"""# -------------------------------
# 11. Final Conclusion
# -------------------------------
"""

print("\n========== CONCLUSION ==========")
print("1. Call drop rate increases during high traffic.")
print("2. Weather conditions significantly affect network quality.")
print("3. Certain time slots and sites need optimization.")
print("4. Visual EDA helps identify problem areas clearly.")